import { WorkspaceHeader } from "@/components/AgriShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BarChart3, Download, FileText, Loader2, Package, ReceiptText } from "lucide-react";
import { buildCsv } from "../../../shared/reportCsv";

const peso = (cents: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(cents / 100);
function downloadCsv(filename: string, rows: Array<Array<string | number>>) { const url = URL.createObjectURL(new Blob([buildCsv(rows)], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

export default function Reports() {
  const { user, loading } = useAuth(); const { data: overview, isLoading, error } = trpc.admin.overview.useQuery(undefined, { enabled: !!user && user.role === "admin" });
  if (loading || isLoading) return <div className="grid min-h-screen place-items-center bg-[#f8f5ee]"><Loader2 className="animate-spin text-[#4e8257]"/></div>;
  if (!user || user.role !== "admin") return <><WorkspaceHeader title="Platform reports" description="Export platform-wide marketplace reports."/><main className="mx-auto max-w-3xl px-4 py-10"><div className="agri-card p-8 text-center"><h1 className="font-display text-3xl font-bold text-[#254f37]">System administrator access required</h1><p className="mt-3 text-[#65766b]">Only system administrators can export platform-wide marketplace reports.</p></div></main></>;
  const totalSales = overview?.transactions.reduce((sum, transaction) => sum + transaction.amountCents, 0) || 0;
  const reports = [
    { title: "Sales report", body: "Completed transaction totals and payment method/status records.", icon: BarChart3, value: peso(totalSales), export: () => downloadCsv("agricoop-sales-report.csv", [["Transaction ID", "Order ID", "Amount", "Payment reference", "Status", "Completed"], ...(overview?.transactions || []).map(transaction => [transaction.id, transaction.orderId, peso(transaction.amountCents), transaction.paymentReferenceNote || `${transaction.paymentMethod || "f2f"} payment`, transaction.status, String(transaction.completedAt || "")])]) },
    { title: "Inventory report", body: "All product listings with status, stock, and current unit price.", icon: Package, value: String(overview?.products.length || 0), export: () => downloadCsv("agricoop-inventory-report.csv", [["Product ID", "Product", "Category", "Stock", "Unit", "Price", "Status"], ...(overview?.products || []).map(product => [product.id, product.name, product.category, product.stockQty, product.unit, peso(product.priceCents), product.status])]) },
    { title: "Quotation report", body: "Quotation requests, response status, and confirmed prices where available.", icon: FileText, value: String(overview?.quotations.length || 0), export: () => downloadCsv("agricoop-quotation-report.csv", [["Quotation ID", "Product ID", "Buyer ID", "Seller ID", "Quantity", "Quoted price", "Status", "Requested"], ...(overview?.quotations || []).map(quotation => [quotation.id, quotation.productId, quotation.buyerId, quotation.sellerId, quotation.requestedQty, quotation.quotedPriceCents ? peso(quotation.quotedPriceCents) : "Pending", quotation.status, String(quotation.createdAt)])]) },
    { title: "Transaction report", body: "Traceable transaction records with order references, payment method, and status.", icon: ReceiptText, value: String(overview?.transactions.length || 0), export: () => downloadCsv("agricoop-transaction-report.csv", [["Transaction ID", "Order ID", "Buyer ID", "Seller ID", "Amount", "Payment reference", "Status"], ...(overview?.transactions || []).map(transaction => [transaction.id, transaction.orderId, transaction.buyerId, transaction.sellerId, peso(transaction.amountCents), transaction.paymentReferenceNote || `${transaction.paymentMethod || "f2f"} payment`, transaction.status])]) },
  ];
  return <><WorkspaceHeader title="Platform reports" description="Generate administrative CSV reports for sales, inventory, quotations, and transactions."/><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-3xl bg-[#1f4f36] p-7 text-[#fffdf8]"><p className="text-xs font-extrabold uppercase tracking-[.13em] text-[#bed99c]">System administrator</p><h1 className="mt-2 font-display text-4xl font-bold">Operational reports, ready to share.</h1><p className="mt-3 max-w-2xl text-[#d7e7d4]">Each report is exported as a CSV file for review, cooperative reporting, and traceable record keeping. AgriCoop records F2F fallback and PayMongo sandbox payment methods, with provider confirmation synchronized by webhook.</p></div>{error ? <p className="mt-6 rounded-xl bg-[#fff1ec] p-4 text-sm text-[#a34838]">{error.message}</p> : <div className="mt-8 grid gap-5 md:grid-cols-2">{reports.map(report => { const Icon = report.icon; return <article key={report.title} className="agri-card p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eaf3e5] text-[#4a804c]"><Icon size={21}/></span><p className="mt-5 text-sm font-bold text-[#66806b]">{report.title}</p><p className="mt-2 font-display text-3xl font-bold text-[#254f37]">{report.value}</p><p className="mt-3 min-h-12 text-sm leading-6 text-[#65766b]">{report.body}</p><button className="agri-button mt-5 text-sm" onClick={report.export}><Download size={16}/> Download CSV</button></article>; })}</div>}</main></>;
}
